#
# Module manifest for module 'PS-Umbrella'
# Generated by: Chris Stone <chris@stoneyforest.net>
# Generated on: 08/23/2022
#

@{
    RootModule = 'PS-Umbrella.psm1'
    ModuleVersion = '0.1'
	# CompatiblePSEditions = @()
    GUID = '9835d8f6-acd2-4824-a4e1-54cbf5925004'
    Author = 'Chris Stone'
	Copyright = '(c) 2022 Chris Stone <chris@stoneyforest.net>. All rights reserved.'
    Description = 'Powershell Module for Cisco Umbrella API.'

    FunctionsToExport = @()
	CmdletsToExport = @()
	VariablesToExport = '*'
	AliasesToExport = @()

	PrivateData = @{
		PSData = @{

			# Tags applied to this module. These help with module discovery in online galleries.
			# Tags = @()

			# A URL to the license for this module.
			# LicenseUri = ''

			# A URL to the main website for this project.
			# ProjectUri = ''

			# A URL to an icon representing this module.
			# IconUri = ''

			# ReleaseNotes of this module
			# ReleaseNotes = ''

		} # End of PSData hashtable

	} # End of PrivateData hashtable

}
